### ISSUE TITLE
Emulating constraint modification

### ISSUE THREAD

**Issue by IssamT** [JuliaOpt/LinQuadOptInterface.jl#14]
In CLP it is possible to modify the coefficients in the objective. It is also possible to modify the RHS of a constraint. But I couldn't find a function for direct modification of constraint coefs. 

```Cpp
     /** Change row lower bounds */
     COINLIBAPI void COINLINKAGE Clp_chgRowLower(Clp_Simplex * model, const double * rowLower);
     /** Change row upper bounds */
     COINLIBAPI void COINLINKAGE Clp_chgRowUpper(Clp_Simplex * model, const double * rowUpper);
     /** Change column lower bounds */
     COINLIBAPI void COINLINKAGE Clp_chgColumnLower(Clp_Simplex * model, const double * columnLower);
     /** Change column upper bounds */
     COINLIBAPI void COINLINKAGE Clp_chgColumnUpper(Clp_Simplex * model, const double * columnUpper);
     /** Change objective coefficients */
     COINLIBAPI void COINLINKAGE Clp_chgObjCoefficients(Clp_Simplex * model, const double * objIn);
```

https://github.com/coin-or/Clp/blob/master/Clp/src/Clp_C_Interface.h#L128

The only way to do it is by deleting a constraint (the one to update) and adding a new one (the updated one). However this will mess up the row indices and I guess will not work with LQOI. Is there a reasonable way around this ? Deleting all the constraints below the one to update and adding them after the updated one isn't a good one.

**Comment by odow** [comment]
You don't have to implement the full interface. If Clp doesn't support it. Don't wrap it :)

Feel free to add an API method for constraint coefficient modification.

**Comment by IssamT** [comment]
You're right. 

For CLP, the best solution is probably exposing the following C++ method through the C interface.

```Cpp
     /// Modify one element of a matrix
     inline void modifyCoefficient(int row, int column, double newElement,
                                   bool keepZero = false) {
          matrix_->modifyCoefficient(row, column, newElement, keepZero);
     }
```

However if some solver really doesn't support such modification, we could add a test config option to handle modification of constraint coefs as delete/add.

**Comment by odow** [comment]
I'm re-opening as a reminer until an API method is implemented.

**Comment by odow** [comment]
I would also say, just focus on wrapping the basic C API that is already exposed [here](https://github.com/JuliaOpt/Clp.jl/blob/master/src/ClpCInterface.jl) as a start.

**Comment by IssamT** [comment]
Oh I thought you meant to implement the C API method. But apparently I misunderstood.

Could you please specify which API method you would like to see implemented?

What do you think about the test config option I suggested to add in MOI tests?

**Comment by odow** [comment]
API method to change objective coefficients was implemented by
https://github.com/JuliaOpt/LinQuadOptInterface.jl/pull/15/files#diff-336edfb0d46e995fff3e06669a6df217R221
and https://github.com/JuliaOpt/MathOptInterface.jl/pull/376 added the test config option so I think we're good to close this. Please re-open if there is something else I missed.
