### ISSUE TITLE
Shifting rows of vector constraints

### ISSUE THREAD

**Issue by IssamT** [JuliaOpt/LinQuadOptInterface.jl#18]
I believe the shifting of the following dicts is missing in `shift_references_after_delete_affine!` 
https://github.com/JuliaOpt/LinQuadOptInterface.jl/blob/master/src/LinQuadOptInterface.jl#L116

```julia
    # vectors of rows in constraint matrix
    nonnegatives::Dict{VLCI{MOI.Nonnegatives}, Vector{Int}}
    nonpositives::Dict{VLCI{MOI.Nonpositives}, Vector{Int}}
    zeros::Dict{VLCI{MOI.Zeros}, Vector{Int}}
```

About the following dicts, I am wondering why the value type is `Vector{Int}` and not `Vector{VarInd}`. Also the comment is not correct since these represent bounds and not rows in the constraint matrix.

```julia
    # vectors of rows in constraint matrix
    vv_nonnegatives::Dict{VVCI{MOI.Nonnegatives}, Vector{Int}}
    vv_nonpositives::Dict{VVCI{MOI.Nonpositives}, Vector{Int}}
    vv_zeros::Dict{VVCI{MOI.Zeros}, Vector{Int}}
```

**Comment by odow** [comment]
> I believe the shifting of the following dicts is missing

Yes they probably are. We need better tests in MOI.

> Also the comment is not correct since these represent bounds and not rows in the constraint matrix.

It looks like these are implemented as constraints, e.g., `Ix <= 0`.
https://github.com/JuliaOpt/LinQuadOptInterface.jl/blob/d1ff1ae58d36aad836e852fcfa851d3b450f67c8/src/constraints/vectorofvariables.jl#L24

**Comment by joaquimg** [comment]
We decided that vectorofvariables in nonpositives should be constraints.
If the user wants variable bound he should set variable by variable.
