### ISSUE TITLE
Probable bugs / incorrect behaviour

### ISSUE THREAD

**Issue by odow** [JuliaOpt/LinQuadOptInterface.jl#21]
Listing these off the top of my head as things that aren't implemented correctly:

- adding different bounds:
  - [x] confirmed
  - [ ] fixed
  - [ ] tests
```julia
x = addvariable!(m)
c = addconstraint!(m, SingleVariable(m), LessThan(1.0))
addconstraint!(m, SingleVariable(m), LessThan(0.0))  # this should error
# instead
modify!(m, c, LessThan(0.0))
```

- adding different variable types:
  - [x] confirmed
  - [ ] fixed
  - [ ] tests
```julia
x = addvariable!(m)
c = addconstraint!(m, SingleVariable(m), ZeroOne())
addconstraint!(m, SingleVariable(m), Semiinteger(2,4))  # this should error
# instead
transform!(m, c, Semiinteger(2,4))
```

**Comment by IssamT** [comment]
@odow is right about the first point. Now the second bound is overriding the first one which is not what was discussed here: https://github.com/JuliaOpt/MathOptInterface.jl/issues/56. I assume the following is allowed though. Or should it be declared as interval bound?

```julia
addconstraint!(m, SingleVariable(x), LessThan(5.0))
addconstraint!(m, SingleVariable(x), GreaterThan(1.0))
```

I think we can fix this on the LQOI level by

1) using the existing dicts https://github.com/JuliaOpt/LinQuadOptInterface.jl/blob/master/src/LinQuadOptInterface.jl#L60. But this will not be efficient.

2) adding another datastructure to test for existing bounds faster.

**Comment by joaquimg** [comment]
@IssamT 's example is valid, its certainly not an error.

@odow does MOI explicitly say that thos should result in errors?

If it does, I agree with @IssamT , testing that all the time would be a pain.

We could assume there is an initial constraint at inifinity and then only modify. (or even adding is tested but modifying is not - we need to check if that is compatible with JuMP though...)

Or we could add a parameter do LQOI models: `TEST_EXISTING_VARIABLE_BOUNDS`, which could be set to false. It would be simpler than adding a faster structure at this moment.

**Comment by IssamT** [comment]
The doc doesn't say exactly that solvers must raise an error when such constraint is defined twice. It only allows it, with the other alternative being to stack them.
> solvers can safely choose to not support the following constraints:
> ... 
> Two SingleVariable-in-LessThan constraints applied to the same variable (similarly with GreaterThan). These should be interpreted as variable bounds, and each variable naturally has at most one upper or lower bound. 

https://github.com/JuliaOpt/MathOptInterface.jl/blob/master/docs/src/apimanual.md#implementing-a-solver-interface

> We could assume there is an initial constraint at inifinity and then only modify

I believe this solution has a con of making the "bound constraint" inconsistent with the other constraints in MOI.

> Or we could add a parameter to LQOI models

I like this solution. it is similar to the philosophy of `@inbounds` for arrays. And the overriding solution could be the "undefined behavior" in this case.

**Comment by odow** [comment]
We either (1) keep track of all bounds that are added and update the bound anytime one is modified, added, or deleted; or (2) throw an error. 

(1) seems like a lot of work and a high surface area for bugs. 
(2) can be implemented easily.

I think we should implement (2) and leave (1) for future work.

**Comment by odow** [comment]
How often do you add multiple bounds? It's no more effort than checking if the current bound is the least upper, and dealing with all the duals.

**Comment by joaquimg** [comment]
Sometime I don't even query duals because of the time it takes between solves, also between solves I change many variable bounds.

**Comment by joaquimg** [comment]
2hours if you are running for 2 days hehehe. 4% here 5% there... in the end you are 30% faster... I am ok doing most of that manually :) or improving with some performance hints in the future. Lets do it!

**Comment by joaquimg** [comment]
@odow I agree those errors are confirmed.
Your plans is adding unit tests for errors in MOI?

**Comment by odow** [comment]
> Your plans is adding unit tests for errors in MOI?

Yes, unless you are volunteering to do so :)

**Comment by joaquimg** [comment]
I will fix the issues and open a PR, can you do the tests?
