### ISSUE TITLE
Separating Quadratic and linear constraints

### ISSUE THREAD

**Issue by joaquimg** [JuliaOpt/LinQuadOptInterface.jl#25]
Xpress does not separates quadratic from linear constraints like Gurobi does.

I would like to modify LQOI to have

`addquadraticconstraint!(m, func, set)`
and
`addlinearconstraint!(m, func, set)`

returning the indices to be stored in the Constraints Dictionaries

**Comment by odow** [comment]
maybe the solvers should store and manage the index-row map

**Comment by joaquimg** [comment]
I made a local fix by:
1) replace uses of get_number_linear... by get_last_linear_index
2) abstract the deleting function just a little
3) m.constraint_primal_solution = m.qconstraint_primal_solution (fixing the same pointer in the specilized `empty` so that - this only changed in Xpress API)
The first two are the only changes in LQOI with reasonable fallbacks.
I will think about it and submit a PR.
Seems easier than keeping track of another map of indexes.

**Comment by joaquimg** [comment]
another map might be more explict...

**Comment by odow** [comment]
Yea this seems like it should be implemented on the Xpress backend since it is Xpress specific. It shouldn't take too much. It is just two vectors.

**Comment by joaquimg** [comment]
Xpress now does the separation of row types
