### ISSUE TITLE
Supporting constraint function replacement

### ISSUE THREAD

**Issue by rdeits** [JuliaOpt/LinQuadOptInterface.jl#32]
I noticed that it's not currently possible to replace the constraint function in an LQOI-based optimizer: 

```julia
optimizer = GLPK.GLPKOptimizerLP()
x = MOI.addvariables!(optimizer, 2)
f = MOI.ScalarAffineFunction(MOI.ScalarAffineTerm.([1., 2.], x), 0.0)
c = MOI.addconstraint!(optimizer, f, MOI.LessThan(2.0))

f2 = MOI.ScalarAffineFunction(MOI.ScalarAffineTerm.([2., 1.], x), 0.0)
MOI.set!(optimizer, MOI.ConstraintFunction(), c, f2)
```

gives: 

```
ArgumentError: ModelLike of type GLPK.GLPKOptimizerLP does not support setting the attribute `ConstraintFunction`

Stacktrace:
 [1] hidden_set!(::GLPK.GLPKOptimizerLP, ::MathOptInterface.ConstraintFunction, ::MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.LessThan{Float64}}, ::MathOptInterface.ScalarAffineFunction{Float64}) at /home/rdeits/locomotion/explorations/simple-qp-miqp/packages/v0.6/MathOptInterface/src/attributes.jl:588
 [2] set!(::GLPK.GLPKOptimizerLP, ::MathOptInterface.ConstraintFunction, ::MathOptInterface.ConstraintIndex{MathOptInterface.ScalarAffineFunction{Float64},MathOptInterface.LessThan{Float64}}, ::MathOptInterface.ScalarAffineFunction{Float64}) at /home/rdeits/locomotion/explorations/simple-qp-miqp/packages/v0.6/MathOptInterface/src/attributes.jl:279
```

However, given that LQOI does support modifying individual coefficients of constraints, I think it ought to be possible to make this work at least when swapping out one affine function for another by writing a method that internally calls `modify!`. I haven't tried using `modify!` myself yet, but I'm willing to give it a try is my assumptions about this being possible and beneficial are correct.

**Comment by rdeits** [comment]
Ok, after bashing my head against this for a while, the biggest problem is that if a user asks to `set(..., ::ConstraintFunction)`, we need to do several things in LQOI: 

1. Look up the existing constraint function from the inner model, and allocate a Julia object for the result
2. If the previous constraint and the replacement have different sparsity patterns, then: 
  1. Use  `modify()` to zero out every coefficient in the old constraint
3. Use `modify()` to set every coefficient in the replacement constraint

Step (1) is particularly expensive, and that ends up dominating the runtime of the `set()` call. It's also something we *could* avoid, if we had stored the previous constraint function the last time it was set. 

I think the best thing to do would be for LQOI to store the current `ScalarAffineFunction` and `VectorAffineFunction` for each constraint (by adding another field or two to the LinQuadOptimizerBase definitions). Storing the current constraint would let us skip step (1) entirely, which would make setting new constraint functions relatively cheap. 

What do you think?

**Comment by odow** [comment]
We originally decided against storing copies of the functions since this would massively increase memory usage. In some situations, JuMP will have a copy, LQOI will have a copy, and Gurobi will have a copy.

This was one common gripe with the current version of JuMP.

It is unfortunate that getting the constraint function is more expensive, but I guess it comes down to a memory/time trade-off.

**Comment by rdeits** [comment]
In that case, what about an `unsafe_set()` or an additional argument to `set(..., ::ConstraintFunction)` which a frontend can use when it knows the sparsity pattern is unchanged?

**Comment by odow** [comment]
Is there any reason why you can't write a loop in your QP code to modify the coefficients rather than replacing the function? We can leave the slow route for setting the ConstraintFunction.

**Comment by joaquimg** [comment]
If you are using CachingOptimizer upstream, you should be able to get a stored constraint (right? I never tried). But then you have two copies of your model.

**Comment by rdeits** [comment]
@odow yeah, that's an option. Ideally, though, I'd love to solve this at the LQOI level so that the frontends can just happily set the constraint function if that's what they want to do. 

@joaquimg I think that's true. In fact, if we wanted to get really fancy, we could implement `MOI.set!(m::CachingOptimizer{<:LinQuadOptimizer}, ::ConstraintFunction, ...)` to look up the previous constraint in the cache and then do the appropriate coefficient modification

But maybe the best thing to do right now would just be to try to make reconstructing the previous constraint as efficient as possible.

**Comment by joaquimg** [comment]
Having this function working as fast as possible is good. As long as we don´t have to store extra data (`ScalarAffineFunction`s).
Some unsafe setter, might be the simplest solution.
