### ISSUE TITLE
Missing type for `inner` attribute

### ISSUE THREAD

**Issue by rdeits** [JuliaOpt/LinQuadOptInterface.jl#38]
I've been working on some model-predictive control problems using various QP solvers, and so I'm trying to tackle various performance issues with MOI, LQOI, and the solver wrappers. 

The `inner` field defined by the `LinQuadOptimizerBase` macro has no declared type, so any access of that field can only be inferred as `::Any`. In playing around with the Gurobi interface, I've noticed that a lot of functions, including ones that might be used in a relatively hot loop, are type-unstable as a result of that missing declaration. 

Can I ask why that field is left un-typed? I realize it might be tricky to do with the `@def` macro, since it's solver-dependent, but type-instability in all of the inner solver methods seems like an important problem.

For an example of the performance loss caused by this type-instability, we can try just getting the number of constraints in a model in Gurobi:

```julia
using Gurobi
using MathOptInterface
const MOI = MathOptInterface
using LinQuadOptInterface
const LQOI = LinQuadOptInterface
using BenchmarkTools

optimizer = GurobiOptimizer()
@btime LQOI.get_number_linear_constraints($optimizer)
```

which gives: `71.544 ns (1 allocation: 16 bytes)`. 

By changing that field to `inner::Model`, I get `58.896 ns (1 allocation: 16 bytes)`, or about a 20% improvement in runtime. 

Avoiding this performance penalty would require either: 

1. Annotating the `inner` field with the actual type for each solver. This could be accomplished by removing it from the `LinQuadOptimizerBase` definitions and just adding a typed field in each individual solver. 
2. Adding a type-assert to all usages of `model.inner` in the solver wrappers (e.g. `model.inner::Model`in Gurobi.jl) 

(2) is non-breaking but pretty noisy. (1) is harder to gracefully adopt but doesn't require type annotations throughout the code. 

Any thoughts?

**Comment by odow** [comment]
I think @joaquimg wrote it initially. Macro that makes a macro :( 
It should be possible to pass an argument that sets the type parameter?

So then you can go `LQOI.@LinQuadOptimizerBase Model`

**Comment by joaquimg** [comment]
the good thing about that macro is making sure all solve have some minimal fields, so that LQOI can be modified with minimum effect on solvers. That's why I would not support start putting parameters out for now.

I agree that typing everywhere is very annoying (morever we would have to do that for all solvers).

Can we pass that type as a parameter to the `@def`? (I copied this last one from discourse)

**Comment by rdeits** [comment]
I think we can make it a parameter, yeah. I'll give it a try
