### ISSUE TITLE
Remove or Add Nullables dependency

### ISSUE THREAD

**Issue by joaquimg** [JuliaOpt/LinQuadOptInterface.jl#42]
Clp.jl is breaking on 0.7 because of: `single_obj_var::Nullable{MOI.VariableIndex}` as noted by @IssamT https://github.com/JuliaOpt/Clp.jl/pull/27#issuecomment-408943071

I would like to avoid unnecessary dependencies on LQOI, Is that much better than having a flag or something else?

cc @odow @tkoolen @rdeits

**Comment by tkoolen** [comment]
Nullables is currently broken on 0.7, just FYI.

**Comment by odow** [comment]
Can't we just make this `Union{Nothing, MOI.VariableIndex}`?

**Comment by joaquimg** [comment]
Thats the solution for 0.7, but poor performance on 0.6

**Comment by odow** [comment]
We're moving to 0.7 anyway. And how often are `SingleVariable` objectives used?

**Comment by tkoolen** [comment]
There's also the pattern of

```julia
using Compat
struct Foo
    x::Union{Nothing, Float64}
end

function bar(foo::Foo)
    if foo.x isa Float64
        return foo.x::Float64 * 3
    else
        return 0
    end
end

using BenchmarkTools
@btime bar(foo) setup = foo = Foo(rand(Bool) ? rand() : nothing)
```

The `isa` followed by a type assertion makes it so that on 0.6:

```julia
  2.738 ns (0 allocations: 0 bytes)
```
