### ISSUE TITLE
Int but Cchar

### ISSUE THREAD

**Issue by IssamT** [JuliaOpt/LinQuadOptInterface.jl#47]
example:

`change_variable_types!(instance::GurobiOptimizer, columns::Vector{Int}, vtypes::Vector{Cchar})`

To be more consistent we should either use `CInt` (i.e., `Int32`) or use `Char`. Right?

**Comment by odow** [comment]
Solvers should overload the relevant `backend_type` method:

https://github.com/JuliaOpt/LinQuadOptInterface.jl/blob/8da1f509cf80f2ae386e65bcda8d431714dcc9a7/src/solver_interface.jl#L71

It doesn't have to be a `Cchar`.
