### ISSUE TITLE
Uninitialized data when handling vector functions with empty rows

### ISSUE THREAD

**Issue by rdeits** [JuliaOpt/LinQuadOptInterface.jl#48]
Adding a `VectorAffineFunction` constraint to a model can cause uninitialized memory issues if that affine function has any empty rows (rows for which there is no `VectorAffineTerm`. I think the logic here isn't quite right: https://github.com/JuliaOpt/LinQuadOptInterface.jl/blob/e19c941b8005eb35d3b5d658fed40a63f12067ed/src/constraints/vectoraffine.jl#L36-L46 . When a row has no corresponding term, `row_pointers` is not set correctly, and the last element in `row_pointers` will just be left as `undef` (in this case, a random uninitialized `Int`). 

Here's a simple case to reproduce the issue: 

```julia
using Gurobi
using MathOptInterface
const MOI = MathOptInterface

model = GurobiOptimizer()
x = MOI.addvariables!(model, 1)
MOI.addconstraint!(model, 
    MOI.VectorAffineFunction(
        MOI.VectorAffineTerm.(2, MOI.ScalarAffineTerm.([1.0], x)),
        zeros(2)
    ), 
    MOI.Nonnegatives(2)
)
```

Running the above will either produce a Gurobi error code 10018 ("problem adding constraints") or an `InexactError()`, with the behavior varying based on whatever the uninitialized memory ended up as.

**Comment by rdeits** [comment]
I think that function can also be cleaned up a bit using `MOIU.canonical()`

**Comment by odow** [comment]
I want to remove all of these functions in favour of using a bridge such as https://github.com/JuliaOpt/MathOptInterface.jl/pull/413, precisely because there are so many edge-case bugs that are easier to test and analyse as a bridge.

**Comment by rdeits** [comment]
Ok, seems reasonable. I'm still going to try to fix this today, though, because I need it to work :slightly_smiling_face:
