### ISSUE TITLE
Support for SecondOrderCone set

### ISSUE THREAD

**Issue by tkoolen** [JuliaOpt/LinQuadOptInterface.jl#78]
I noticed there's no code for `SecondOrderCone` constraint sets yet. Are there any plans for adding support for that in LQOI? Or should that be done separately in the individual solver packages that support SOCP constraints?

**Comment by blegat** [comment]
Do you have an example of solver natively supporting SOC and using LQOI.
There is a SOCtoQuadBridge under discussion in a MOI PR

**Comment by tkoolen** [comment]
Hmm, good point :slightly_smiling_face:. I thought Gurobi did, but I guess it just does quadratic constraints. A `SOCtoQuadBridge` would be great.
