### ISSUE TITLE
__assert_dual_sense__ does not use a tolerance

### ISSUE THREAD

**Issue by vitornesello** [JuliaOpt/LinQuadOptInterface.jl#86]
I am using GLPK and CPLEX through LQOI to get the duals of constraints and in some cases I have an `AssertionError` with the message: `"dual >= 0"` (for >= constraints). I went in the LQOI code and found out that is comes from the following lines: 
https://github.com/JuliaOpt/LinQuadOptInterface.jl/blob/7f4d09bf834f1ba3e2938397dbfae5c7108fe281/src/solve.jl#L209
https://github.com/JuliaOpt/LinQuadOptInterface.jl/blob/7f4d09bf834f1ba3e2938397dbfae5c7108fe281/src/solve.jl#L210

When I add an eps in the assetion:
``` julia
__assert_dual_sense__(::LCI{LE}, dual) = @assert dual <= 0.0 + 1e-7
__assert_dual_sense__(::LCI{GE}, dual) = @assert dual >= 0.0 - 1e-7
```

I have no problems and the code runs correctly.

**Comment by odow** [comment]
Want to make a pull request?

**Comment by mlubin** [comment]
These asserts seem inappropriate. How does LQOI know what tolerances the solver is using?

**Comment by joaquimg** [comment]
I agree that feasibility check should be a separate step

**Comment by odow** [comment]
These should be covered by MOI tests anyway.

**Comment by vitornesello** [comment]
So what should I do to fix this? Do you always "trust" the solvers underneath? If you do, I see no reason to have these assertions. Also, it removes the control from the user to accept or not a result that is an epsilon > 0.
For me this should be consistent with the way `get(::VariablePrimal)` works, for example. Do you check whether the solver returns a feasible primal value when variables are bounded?

**Comment by blegat** [comment]
@vitornesello The assert should just be removed IMO

**Comment by odow** [comment]
Closed by #87

**Comment by geoffleyland** [comment]
Hi!  I see this has been fixed in master, but as far as I can tell, it's not in any release.  Are there any plans for a new release containing this fix?

**Comment by odow** [comment]
Which solver are you using? We've rewritten the solvers to get rid of LQOI.

**Comment by geoffleyland** [comment]
This is using Clp, and ... JuMP 0.19.2.  Hadn't seen 0.20 was out, and had made the assumption that I needed a new LQOI anyway.  I'll update, and get back to you.

**Comment by odow** [comment]
Clp hasn't been updated, but GLPK has, so you can try that.

```Julia
] add GLPK
```
Then replace `Clp.Optimizer` with `GLPK.Optimizer`.

**Comment by geoffleyland** [comment]
Thanks!  That did exactly what it said on the box.
