### ISSUE TITLE
ListOf[XXX]AttributesSet

### ISSUE THREAD

**Issue by odow** [JuliaOpt/LinQuadOptInterface.jl#90]
@blegat what should this be? `VariableName`?
https://github.com/JuliaOpt/LinQuadOptInterface.jl/blob/83213683fcb527a4ee45dc7fe32c4aa9e1d9f4a1/src/LinQuadOptInterface.jl#L214-L216

Ditto here?
https://github.com/JuliaOpt/LinQuadOptInterface.jl/blob/83213683fcb527a4ee45dc7fe32c4aa9e1d9f4a1/src/LinQuadOptInterface.jl#L229-L231

**Comment by blegat** [comment]
Yes, like in the MOIU model:
https://github.com/JuliaOpt/MathOptInterface.jl/blob/05b79b7ca59049c930cfdd4476fa06ab0d447559/src/Utilities/model.jl#L284
An attribute should be included in the list iff it is copyable:
```julia
julia> using MathOptInterface

julia> const MOI = MathOptInterface
MathOptInterface

julia> MOI.is_copyable(MOI.VariableName())
true
```
so it should be included
